package com.tbfp.teamplannerbe.domain.notification.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.tbfp.teamplannerbe.config.dynamodb.DynamoDBConfig;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "notification")
@Setter
@ToString
public class Notification{


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String recruitmentProfileImage;

    @DynamoDBAttribute
    private String content;
    @DynamoDBAttribute
    private Long memberId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime createdAt;
}