version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cityweb
hooks:
  BeforeInstall:
    - location: scripts/setup_docker.sh
    - location: scripts/init_docker.sh
    - location: scripts/init_server.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/pull_docker.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root

