version: "3.7"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - springboot-mysql-net

  test-app:
    image: 129715120090.dkr.ecr.ap-northeast-2.amazonaws.com/teamplanner-backendserver:latest
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      jasypt.encryptor.password: ${JASYPT_KEY}
    depends_on:
      - redis
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge