  version: "3.7"

  services:
    db-mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: testdb
        MYSQL_ROOT_HOST: "%"
        MYSQL_ROOT_PASSWORD: 1234
      ports:
        - 3306:3306
      command:
        - "mysqld"
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_unicode_ci"
      networks:
        - springboot-mysql-net

    redis:
      image: redis
      ports:
        - 6379:6379
      networks:
        - springboot-mysql-net

    test-app:
      image: springbootapp:latest
      ports:
        - 8080:8080
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/testdb?useSSL=false
        SPRING_DATASOURCE_USERNAME: "root"
        SPRING_DATASOURCE_PASSWORD: 1234
        SPRING_PROFILES_ACTIVE: prod
        jasypt.encryptor.password: 1234zzzz
      depends_on:
        - db-mysql
        - redis
      networks:
        - springboot-mysql-net

  networks:
    springboot-mysql-net:
           driver: bridge
