spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.201.38.39:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ENC(eKdWCOqUWNDBo/xol2H4mA==)
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(RMzRozI9X940vUzLbfZWCrziavdCrVJ9uHuJ37TQYvHq5KLnjqTh0w==)
    password: ENC(274mAiMFCwMnPvWvtwj8Km0UcrBWMrx18Qfy1ySENps=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(thvvcLV+DnQ58aRRXC7hYqhSDR7+itO9duMQq84+FbmMyoPBjZRdpnzNhpQ6PkRZiPYsPldPlhpxBkblYqVu3tDIw10+qgRqGTC58Wh1Ym7VJW0JkwPHwQ==)
            client-secret: ENC(8jxilkxKqm9WG5rHfTZCLnCe2wNlNKQTOgqU+AWLxBJ/VIX39PGXYuIupL+YmKrD)
            scope:
              - profile
              - email
            authorization-grant-type: authorization_code
          kakao:
            client-id: ENC(tIqDwGm2/0M+d9q+cJ90pfEZqcninNW6XS5DM/E3OFlsr2rXOGApp5Ydopezh/TH)
            client-secret: ENC(Fvhw9WH3FB30IohjJ+hrfbLT+7FfZGXjnma0jgO0BNeuXVDQrAGMiiY7V11P0IzU)
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            client-name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  #  redis configuration
  redis:
#    host: localhost
#    port: 6379
    cluster:
      nodes:
        - ENC(QUHVF2B5BpHofqiaC4T5R7Pqizp3H0q8ecxxb9+D9JYN9Bf39zYQDt4rEYEMENA4pDgkVNe3MGGc1XLx/7gGfGa9NBE867bs)
        - ENC(XeOR57LFf6o62GLBsKD0RU4ZFjzoSilSuAOxTadcUj7fLXBHj88iG2ebM4O6ossWYDowPCWPp8lnmCIFjfP39GdO2U8o1zbA)
        - ENC(E4n6dbNNqUTTvAswftF/Jc1QgYX2PSmtTqoBMo7RHukblzn4nRI9paG8qvd0v3KZ0hz0u7NG8RJRuEbzhO5hPiScPJ4eDB4d)
        - ENC(D8tqBVJ0dQQpP2RQ0PJ26vL3nkIFNP24kFV3cur1lrNoCip0zU28VMKj5BOqkOmHWEu3KMt63B4RQQDNg9ltIhIRBSGCQP7s)
        - ENC(Hz1vs4HAYLfPuU71h3AoXbE4ah5GEwyDnGV6/TMlvmiZjppiM9AReM33NqaQvhSM3mNBnQlPQt4kAg03R+z7jaDi7mOgxDfL)
        - ENC(DrY0jzzsvi9oQgQa06Vryk1AcMZwoZ1YqtsHwN5Xv3dBNfx6y0daEmDwWohFYKeAEErXgDzVk3prDgdjGtNMG0EPYjPe2FW+)

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    url: jdbc:mysql://43.201.38.39:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password: ENC(eKdWCOqUWNDBo/xol2H4mA==)

logging.level:

  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret_key: ENC(mmf+mUwEemm7lqzn7MyjYaYVlRpGN25Xpvmo4jQ4ctx7tNdCrjBXR2JdWIZjh6LAupCdrOSI44WtK+dUp4tym1fIiEfdYbNpNudokWdOtKf1JnRMMB8PasGfLDAPofA0uNViAU3SZeK0hd9oeTBo3P+LawaOOimGe4G7FZqQIA0x4B0IIkJx9WGN+O3zam1UZdtcTd4WA0Ojnal1JcjcwDRJ1XcmsDyGHVQ5LSWMN0PydTg0hCd4COYUz5ORRKAE2ytwgmhPF0A=)


springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
