spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(RMzRozI9X940vUzLbfZWCrziavdCrVJ9uHuJ37TQYvHq5KLnjqTh0w==)
    password: ENC(274mAiMFCwMnPvWvtwj8Km0UcrBWMrx18Qfy1ySENps=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(thvvcLV+DnQ58aRRXC7hYqhSDR7+itO9duMQq84+FbmMyoPBjZRdpnzNhpQ6PkRZiPYsPldPlhpxBkblYqVu3tDIw10+qgRqGTC58Wh1Ym7VJW0JkwPHwQ==)
            client-secret: ENC(8jxilkxKqm9WG5rHfTZCLnCe2wNlNKQTOgqU+AWLxBJ/VIX39PGXYuIupL+YmKrD)
            scope:
              - profile
              - email
            authorization-grant-type: authorization_code
          kakao:
            client-id: ENC(tIqDwGm2/0M+d9q+cJ90pfEZqcninNW6XS5DM/E3OFlsr2rXOGApp5Ydopezh/TH)
            client-secret: ENC(Fvhw9WH3FB30IohjJ+hrfbLT+7FfZGXjnma0jgO0BNeuXVDQrAGMiiY7V11P0IzU)
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            client-name: kakao
          naver:
            client-id: ENC(xhkYRfuF4bKKCUZIRGq99vYJOX9R3lGkqRrZTxLQMpg=)
            client-secret: ENC(JRti2SzgyfLocqCL3j0Ld62Q0dhD20SC)
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#  redis configuration
  redis:
    host: localhost
    port: 6379
#    cluster:
#      nodes: ${REDIS_CLUSTER_NODES}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    user: root
    password:

#logging.level:
#
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  secret_key: ENC(mmf+mUwEemm7lqzn7MyjYaYVlRpGN25Xpvmo4jQ4ctx7tNdCrjBXR2JdWIZjh6LAupCdrOSI44WtK+dUp4tym1fIiEfdYbNpNudokWdOtKf1JnRMMB8PasGfLDAPofA0uNViAU3SZeK0hd9oeTBo3P+LawaOOimGe4G7FZqQIA0x4B0IIkJx9WGN+O3zam1UZdtcTd4WA0Ojnal1JcjcwDRJ1XcmsDyGHVQ5LSWMN0PydTg0hCd4COYUz5ORRKAE2ytwgmhPF0A=)


springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

amazon:
  aws:
    endpoint: dynamodb.ap-northeast-2.amazonaws.com
    accessKey: ENC(2c1CtG+taOT9pHnmFuoSHmeL12IrZLyQq6jgNbUFicI=)
    secretKey: ENC(o2AZZVhzY12A7m7Vk8ZorqVENHq1OJO36xmTQk4MZAz0vHbsOwPIiLFpFFikkQdKntNxEE2Bxb0=)
    region: ENC(gGm9/hJVzdCVEEmIdsfDPAnanlIsxaJl)
    bucket: ENC(DY8KvVk0IQLZUQvhbosqcCuw9yOzwVd5ouVEybAZtFk=)

permitUrls:
  get: /api/v1/board/**, /api/v1/recruitment/**, /api/v1/member/signup/**/
  post: /api/v1/member/signup/**, /api/v1/member/forgot-username, /api/v1/member/forgot-password,/api/v1/member/email-verify,/api/v1/member/idEmail-verify
  all: /, /api/v1/member/login, /api/v1/member/renew-access-token, /swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, /api/v1/board,/ws/chat/**
  delete:
  put:
  patch:
