package com.tbfp.teamplannerbe.domain.chat.entity;

import com.amazonaws.services.config.model.MessageType;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.tbfp.teamplannerbe.config.dynamodb.DynamoDBConfig;
import lombok.*;

import javax.persistence.Id;
import java.io.Serializable;
import java.time.LocalDateTime;



@Getter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "chatting")
@Setter
@ToString
public class ChatMessage {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;


    //채팅방 ID
    @DynamoDBAttribute
    private Long roomId;
    //보내는 사람
    @DynamoDBAttribute
    private Long senderId;
    //내용
    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    private Integer readCount;

    public void decreaseReadCount(){
        this.readCount-=1;
    }

}
