drop table if exists chatroom_member;
CREATE TABLE chatroom_member (
    CHATROOM_MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID BIGINT,
    CHATROOM_ID BIGINT,
    FOREIGN KEY (MEMBER_ID) REFERENCES member (MEMBER_ID),
    FOREIGN KEY (CHATROOM_ID) REFERENCES chatroom (CHATROOM_ID)
) engine=InnoDB;